<?php

namespace Diolan12;

/**
 * A class that represents a network of cable routes.
 * Generated by OpenAI ChatGPT [Mar 14 Version](https://help.openai.com/en/articles/6825453-chatgpt-release-notes)
 */
class Dijkstra
{
    private $prefix = '#';
    private $vertices = [];

    public function __construct($graph = [])
    {
        $prefixedVertices = [];
        foreach ($graph as $k => $edges) {
            $prefixedName = $this->setPrefix($k);
            $prefixedVertices[$prefixedName] = [];
            foreach ($edges as $edgeKey => $edgeValue) {
                $prefixedVertices[$prefixedName][$this->setPrefix($edgeKey)] = $edgeValue;
            }
        }
        $this->vertices = $prefixedVertices;
    }

    private function setPrefix(string $value)
    {
        return $this->prefix . $value;
    }
    private function unPrefix(string $value)
    {
        return substr($value, 1);
    }

    /**
     * Return Dijkstra's instance
     * @return \Diolan12\Dijkstra
     */
    public static function instance($graph = [])
    {
        return new self($graph);
    }

    /**
     * Add a vertex to the graph with its neighboring edges.
     *
     * @param string $name The name of the vertex.
     * @param array $edges An associative array representing the neighboring vertices and their edge weights.
     * @return \Diolan12\Dijkstra
     */
    public function addVertex($name, $edges)
    {
        $prefixedName = [];
        foreach ($edges as $key => $value) {
            $prefixedName[$this->setPrefix($key)] = $value;
        }
        $this->vertices[$this->setPrefix($name)] = $prefixedName;
        return $this;
    }

    /**
     * Add an edge between two vertices with a given weight.
     *
     * @param string $src The source vertex.
     * @param string $dest The destination vertex.
     * @param int $weight The weight or cost of the edge.
     * @param bool $reversible (optional) Whether the edge is reversible. Default is false.
     * @throws \InvalidArgumentException if the weight is negative.
     * @return \Diolan12\Dijkstra
     */
    public function addEdge($src, $dest, $weight, $reversible = false)
    {
        if ($weight < 0) throw new \InvalidArgumentException('Weight must be non-negative.');
        $this->vertices[$this->setPrefix($src)][$this->setPrefix($dest)] = $weight;
        if ($reversible) {
            $this->vertices[$this->setPrefix($dest)][$this->setPrefix($src)] = $weight;
        }
        return $this;
    }

    /**
     * Dijkstra's shortest path algorithm
     * [Wikipedia](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)
     * @see https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm
     * @throws \Diolan12\NoPathException
     */
    public function findShortestPath($start, $end)
    {
        $startPrefix = $this->setPrefix($start);
        $endPrefix = $this->setPrefix($end);

        $distances = [];
        $previous = [];
        $queue = new \SplPriorityQueue();

        // 1. We need to collect ALL possible vertices (sources and destinations)
        // to initialize distances correctly.
        foreach ($this->vertices as $v => $edges) {
            $distances[$v] = INF;
            foreach ($edges as $neighbor => $cost) {
                $distances[$neighbor] = INF;
            }
        }

        // 2. Check if the start and end actually exist in our graph data
        if (!array_key_exists($startPrefix, $distances) || !array_key_exists($endPrefix, $distances)) {
            throw new NoPathException('Route target not found "' . $this->unPrefix($endPrefix) . '"');
        }

        $distances[$startPrefix] = 0;
        $queue->insert($startPrefix, 0);

        while (!$queue->isEmpty()) {
            $current = $queue->extract();

            if ($current === $endPrefix) break;

            // If we don't have outgoing edges from this node, skip it
            if (!isset($this->vertices[$current])) continue;

            foreach ($this->vertices[$current] as $neighbor => $cost) {
                $alt = $distances[$current] + $cost;

                if ($alt < $distances[$neighbor]) {
                    $distances[$neighbor] = $alt;
                    $previous[$neighbor] = $current;
                    $queue->insert($neighbor, -$alt);
                }
            }
        }

        // 3. Reconstruct path
        $path = [];
        $curr = $endPrefix;

        while ($curr !== null) {
            array_unshift($path, $this->unPrefix($curr));
            if ($curr === $startPrefix) break;
            $curr = isset($previous[$curr]) ? $previous[$curr] : null;
        }

        // If the path doesn't start with our start node, it's a broken route
        if ($path[0] !== (string)$start) {
            throw new NoPathException('Route target not found "' . $this->unPrefix($endPrefix) . '"');
        }

        return $path;
    }
}
