<?php
namespace Diolan12\Dijkstra;

/**
 * A class that represents a network of cable routes.
 * Generated by OpenAI ChatGPT [Mar 14 Version](https://help.openai.com/en/articles/6825453-chatgpt-release-notes)
 */
class Dijkstra {
    private $vertices = array();
    private $edges = array();

    public function addVertex($name, $edges) {
        $this->vertices[$name] = $edges;
        $this->edges[$name] = array();
        return $this;
    }

    public function addEdge($src, $dest, $weight) {
        $this->edges[$src][$dest] = $weight;
        return $this;
    }

    /**
     * Dijkstra's shortest path algorithm
     * [Wikipedia](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)
     * @see https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm
     * @throws \Exception
     */
    public function findShortestPath($start, $end) {
        $distances = array();
        $visited = array();
        $previous = array();

        foreach ($this->vertices as $vertex => $edges) {
            $distances[$vertex] = INF;
            $visited[$vertex] = false;
            $previous[$vertex] = null;
        }

        $distances[$start] = 0;

        if (!isset($visited[$end])){
            throw new \Exception('Route not found "'.$end.'"', $end);
        }
        while ($visited[$end] === false) {
            $current = null;
            $minDist = INF;

            foreach ($distances as $vertex => $dist) {
                if ($visited[$vertex] === false && $dist <= $minDist) {
                    $minDist = $dist;
                    $current = $vertex;
                }
            }

            foreach ($this->vertices[$current] as $neighbor => $cost) {
                $alt = $distances[$current] + $cost;

                if ($alt < $distances[$neighbor]) {
                    $distances[$neighbor] = $alt;
                    $previous[$neighbor] = $current;
                }
            }

            $visited[$current] = true;
        }

        $path = array();
        $current = $end;

        while ($current !== $start) {
            if ($current == null) {
                throw new \Exception('Route not found "'.$end.'"', $end);
            }
            array_unshift($path, $current);
            $current = $previous[$current];
        }

        array_unshift($path, $start);

        return $path;
    }
}